# Dependencies
#markdown: redcarpet
#highlighter: pygments

# Permalinks
#permalink: pretty
#relative_permalinks: true

# General Info
title: yoonjinxd
email: anazzz1685@gmail.com
description: "Computer Science & Deep Learning"
url: https://yoonjinxd.github.io
baseurl: ""
author:
        name: 'Yoon Jin Chung'
        url: https://github.com/YoonjinXD
        linkedin: https://www.linkedin.com/in/yoonjin-chung-03783016a/
github_username: yoonjinxd
github:
        repo: https://github.com/YoonjinXD/YoonjinXD.github.io

# Build settings
encoding: utf-8
theme: minima
plugins:
  - jekyll-feed
paginate: 5
