# Dependencies
#markdown: redcarpet
#highlighter: pygments

# Permalinks
#permalink: pretty
#relative_permalinks: true

title: Chick's blog
email: anazzz1685@gmail.com
description: "Computer Science & Deep Learning blog"
url: https://yoonjinxd.github.io
baseurl: /
author:
        name: 'Yoon Jin Chung'
        url: https://github.com/YoonjinXD
github_username: YoonjinXD
github:
        repo: https://github.com/YoonjinXD

# Build settings
theme: minima
plugins:
  - jekyll-feed
paginate: 5
