# Dependencies
#markdown: redcarpet
#highlighter: pygments

# Permalinks
#permalink: pretty
#relative_permalinks: true

title: 슬피우는 컴과생
email: anazzz1685@gmail.com
description: "Computer Science & Deep Learning blog"
baseurl: / # the subpath of your site, e.g. /blog
author:
        name: 'Yoon Jin Chung'
        url: "https://github.com/YoonjinXD/" 
github_username: YoonjinXD
github:
        repo: https://github.com/YoonjinXD

# Build settings
theme: minima
plugins:
  - jekyll-feed
paginate: 5
